// Builds core.js: production's engine, data and card code, pulled verbatim (last definition wins, original order).
const acorn=require('acorn'),walk=require('acorn-walk'),fs=require('fs');
const files=['base','v10','v12'];
const stmts=[];
for(const f of files){
  const src=fs.readFileSync('../src-prod/'+f+'.js','utf8');
  const ast=acorn.parse(src,{ecmaVersion:'latest',sourceType:'script'});
  for(const n of ast.body){
    const defs=new Set();
    if(n.type==='FunctionDeclaration')defs.add(n.id.name);
    else if(n.type==='VariableDeclaration')n.declarations.forEach(d=>{if(d.id.type==='Identifier')defs.add(d.id.name)});
    else if(n.type==='ExpressionStatement'&&n.expression.type==='AssignmentExpression'&&n.expression.left.type==='Identifier')defs.add(n.expression.left.name);
    const refs=new Set();
    walk.full(n,(x,st,type)=>{if(x.type==='Identifier')refs.add(x.name)});
    // drop property-key identifiers: re-walk member expressions
    walk.full(n,x=>{
      if(x.type==='MemberExpression'&&!x.computed&&x.property.type==='Identifier'){/* property names may still be globals elsewhere; keep conservative */}
    });
    stmts.push({f,n,src:src.slice(n.start,n.end),defs:[...defs],refs:[...refs]});
  }
}
const ENTRIES=JSON.parse(fs.readFileSync('entries.json','utf8'));
const BLOCK=new Set(JSON.parse(fs.readFileSync('block.json','utf8')));
const byName={};stmts.forEach((s,i)=>s.defs.forEach(d=>(byName[d]=byName[d]||[]).push(i)));
const want=new Set(),queue=[...ENTRIES],inc=new Set(),missing=new Set();
while(queue.length){const nm=queue.pop();if(want.has(nm)||BLOCK.has(nm))continue;want.add(nm);
  const ix=byName[nm];if(!ix){missing.add(nm);continue}
  for(const i of ix){if(inc.has(i))continue;inc.add(i);
    for(const r of stmts[i].refs)if(byName[r]&&!want.has(r)&&!BLOCK.has(r))queue.push(r);}
}
// wrappers like `const __la=loadAll` are defs of __la referencing loadAll: excluded unless wanted
const out=[...inc].sort((a,b)=>a-b).map(i=>stmts[i]);
let code='/* core.js — GENERATED by next-build/tools/extract.js from production index.html. Do not edit by hand. */\n';
let lastF='';
for(const s of out){if(s.f!==lastF){code+='\n/* ===== from '+s.f+' ===== */\n';lastF=s.f}
  let t=s.src;
  if(s.f==='base'&&s.defs[0]==='card'){if(!t.startsWith('function card('))throw new Error('card anchor');t=t.replace('function card(','function __card_base(')+'\nconst __orig={card:__card_base};';}
  code+=t+'\n';}
// ---- the data loader: production loadAll with its UI lines removed (asserted replacements) ----
const base=stmts.find(s=>s.f==='base'&&s.defs[0]==='loadAll').src;
let L=base;
function rep(a,b,label){const c=L.split(a).length-1;if(c!==1)throw new Error('loader anchor '+label+' count '+c);L=L.replace(a,b)}
rep('function loadAll(quiet){','function __loadBase(quiet){','name');
const pillStart=L.indexOf("const pill=document.getElementById('gwpill');");
const pillEnd=L.indexOf("pill.classList.toggle('final',finalMode);");
if(pillStart<0||pillEnd<0)throw new Error('pill block');
L=L.slice(0,pillStart)+"const finalMode=!D.dlPassed&&D.gwsDone>0&&!liveNow&&!D.provOver;D.liveNow=liveNow&&!D.provOver;D.finalMode=finalMode;D.curDl=curDl;"+L.slice(pillEnd+"pill.classList.toggle('final',finalMode);".length);
rep("renderGW();renderTable();renderXIs();renderAct();renderAna();",'','renders');
const qs=L.indexOf('if(!quiet){setTimeout(reopenArticles,0);');const qe=L.indexOf('/* back from an article: the page is tall again */');
if(qs<0||qe<0)throw new Error('quiet block');
L=L.slice(0,qs)+L.slice(qe+'/* back from an article: the page is tall again */'.length);
const cs=L.indexOf('}).catch(e=>{');if(cs<0)throw new Error('catch');
L=L.slice(0,cs)+'});\n}';
code+='\n/* ===== data loader (from base loadAll, UI removed) ===== */\n'+L+'\n';
code+=`
function loadProfilesData(){
  return Promise.all([readTab('Managers').catch(()=>[]),readTab('Specials').catch(()=>[]),readTab('Social').catch(()=>[]),readTab('Posts').catch(()=>[])]).then(([m,sp,so,po])=>{
    /* the AI writer's posts (v3.9); notes are its memory only */
    D.aiPosts=(po||[]).filter(r=>r&&r.Id&&r.Voice&&r.Text&&r.Kind==='ai');
    /* the Social log (v3.8): quotes, reactions, poll votes. A missing tab makes gviz return the first sheet, so keep only real rows */
    D.social=(so||[]).filter(r=>r&&r.Kind&&r.Target&&r.Team);
    const r=(sp||[]).find(x=>x.Setting==='API URL');D.api=r&&r.Value?String(r.Value).trim():'';
    D.managers=m||[];
    Object.keys(PROFILE).forEach(k=>delete PROFILE[k]);
    (m||[]).forEach(r=>{if(!r.Team||!TEAMS[r.Team])return;PROFILE[r.Team]={color:String(r.Color||'').trim(),shape:String(r.Shape||'').trim(),photo:String(r.Photo||'').trim(),manager:String(r.Manager||'').trim(),emblem:String(r.Emblem||'').trim(),pattern:String(r.Pattern||'').trim(),second:String(r.Second||'').trim()};});
  });
}
/* loadData(quiet): everything the pages read lands in D; resolves when ready */
/* auto-subs are a pure function of the loaded data; production memoised them per load (v12 lkFresh) */
let __AS={k:null,m:new Map()};
const __autoSubsRaw=autoSubs;
autoSubs=function(team,likely){const k=[D.ro,D.gwsByGw,D.cf,D.fx,D.gw,D.dlPassed,D.provOver,D.pbonus,D.predCur,D.gl];
  if(!__AS.k||k.some((v,i)=>v!==__AS.k[i])){__AS.k=k;__AS.m=new Map();}
  const ck=team+'|'+(likely?1:0);let c=__AS.m.get(ck);if(!c){c=__autoSubsRaw(team,likely);__AS.m.set(ck,c);}
  return {xi:c.xi.slice(),subs:c.subs.slice()};};
autoSubs.__mdMemo=1;
function loadData(quiet){hpReset();return __loadBase(quiet).then(()=>loadProfilesData()).then(()=>{fixNations();hpReset();buildH2H();LOADED_AT=Date.now();return D;});}
let LOADED_AT=0;
`;
fs.writeFileSync('../core.gen.js',code);
const names=out.map(s=>s.defs.join(',')||'(stmt)');
console.log('statements',out.length,'bytes',code.length);
console.log('missing (globals/builtins):',[...missing].filter(x=>!(x in globalThis)).join(' '));
const ui=names.filter(n=>/^(render|open|update|repaint|show|build|close|push|reopen|lgfx|faq|hero)/.test(n));
console.log('UI-ish included:',ui.join(' '));
fs.writeFileSync('included.txt',names.join('\n'));
